### ISSUE TITLE
'Capture Windows To Disk' crash.

### ISSUE THREAD

**Issue by ThomRichardson** [kangyu-california/PersistentWindows#174]
When trying to capture window positions to disk it cannot find a file and crashes:

![Screen Recording 2022-08-29 at 07 37 12 19 AM](https://user-images.githubusercontent.com/9776564/187202568-466bff6b-e20b-4987-a2f1-6a3105dafb58.gif)

`************** Exception Text **************
System.ComponentModel.Win32Exception (0x80004005): **The system cannot find the file specified**
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at Ninjacrab.PersistentWindows.SystrayShell.Program.GetProcessInfo() in H:\proj\PersistentWindows.orig\sourceCode\persistentwindows\Ninjacrab.PersistentWindows.Solution\Ninjacrab.PersistentWindows.SystrayShell\Program.cs:line 480
   at Ninjacrab.PersistentWindows.SystrayShell.Program.CaptureToDisk() in H:\proj\PersistentWindows.orig\sourceCode\persistentwindows\Ninjacrab.PersistentWindows.Solution\Ninjacrab.PersistentWindows.SystrayShell\Program.cs:line 432
   at Ninjacrab.PersistentWindows.SystrayShell.SystrayForm.CaptureWindowClickHandler(Object sender, EventArgs e) in H:\proj\PersistentWindows.orig\sourceCode\persistentwindows\Ninjacrab.PersistentWindows.Solution\Ninjacrab.PersistentWindows.SystrayShell\SystrayForm.cs:line 268
   at System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
PersistentWindows
    Assembly Version: 5.38.8263.40891
    Win32 Version: 5.38.8263.40891
    CodeBase: file:///D:/PersistWindows/PersistentWindows.exe
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
Ninjacrab.PersistentWindows.Common
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///D:/PersistWindows/Ninjacrab.PersistentWindows.Common.DLL
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4220.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
LiteDB
    Assembly Version: 5.0.9.0
    Win32 Version: 5.0.9
    CodeBase: file:///D:/PersistWindows/LiteDB.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.IO.Compression.FileSystem
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
----------------------------------------
`

**Comment by kangyu-california** [comment]
PW relies on wmic.exe to get process command line in order to restore closed windows.
It sounds like Microsoft has remove wmic.exe in latest windows 11 dev build according to [this article](https://winaero.com/microsoft-removed-the-wmic-tool-from-windows-11-dev-builds/) 
The workaround is
" if you are running an English version of Windows 11, copy the  c:\windows\system32\wbem\wmic.exe and c:\windows\system32\wbem\en-US\wmic.exe.mui from Windows 11 22000 to your current OS under the same location."

I will investigate other ways to retrieve process command line. Estimated fix time is mid Sep.

Thanks

**Comment by kangyu-california** [comment]
Another workaround "Starting with Windows 11 build 22572, WMIC is now available as an optional feature that can be uninstalled or reinstalled via Settings > Apps > Optional Features.
 This tutorial will show you how to add or remove the WMIC optional feature for all users in Windows 11.
 You must be signed in as an administrator to add and remove the WMIX optional feature."
